DATALOADER:
  ROOT: data/
  BATCH_SIZE: 1
  SHUFFLE: True
  NUM_WORKERS: 4
MODEL:
  PRETRAINED: False
  NUM_CLASSES: 2 #Background + Face
OPTIMIZER:
  LEARNING_RATE: 0.00001
LR_SCHEDULER:
  MILESTONES:
  - 12
  - 16
  GAMMA: 0.1
TRAINER:
  NUM_OF_EPOCHS: 20
  SCORE_THRESHOLD: 0.6
  NMS_THRESHOLD: 0.3